### ISSUE TITLE
Chapter2 - Jaeger UI doesn't show services

### ISSUE THREAD

**Issue by chokecoDev** [istioinaction/book-source-code#37]
I followed the steps for Jaeger UI, however when I open the browser Jaeger only showed "jaeger-all-in-one".

**Probable Solution**

1. Create a file `istio-config.yaml` with the following content:

```yaml
apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
spec:
  meshConfig:
    defaultConfig:
      tracing:
        zipkin:
          address: jaeger-collector.istio-system:9411
  components:
    base:
      enabled: true
    egressGateways:
    - enabled: false
      name: istio-egressgateway
    ingressGateways:
    - enabled: true
      name: istio-ingressgateway
    pilot:
      enabled: true
  hub: docker.io/istio
  profile: default
  tag: 1.22.2
  values:
    defaultRevision: ""
    gateways:
      istio-egressgateway: {}
      istio-ingressgateway: {}
    global:
      configValidation: true
      istioNamespace: istio-system
```
This content can be generated with `ìstioctl profile dump`, you must add the meshConfig property.

2. Apply the configuration:

```bash
istioctl install -f istio-config.yaml -y
```

3. Restart deployments:

```bash
kubectl rollout restart deploy webapp
kubectl rollout restart deploy catalog
```

4. Open Jaeger UI
